(function () {
  "use strict";
  const token = new URLSearchParams(window.location.hash.slice(1)).get("token") || "";
  const OVERALL_FILE = "__kmz__";
  const state = { document: null, currentFile: null, currentRoute: null, view: "map", map: null, basemap: null, routeLayer: null, templateLayer: null, labels: [], routeLabels: [], templateLabels: [], bounds: [], globe: null, globeEntities: [] };
  const $ = (id) => document.getElementById(id);
  const api = (path) => fetch(path, { headers: { "X-Preview-Token": token }, cache: "no-store" }).then((r) => { if (!r.ok) throw new Error("数据访问失败"); return r.json(); });
  const text = (value, fallback = "—") => value === null || value === undefined || value === "" ? fallback : String(value);
  const number = (value, digits = 2) => value === null || value === undefined ? "—" : Number(value).toFixed(digits);
  const distance = (value) => value == null ? "—" : value >= 1000 ? `${(value / 1000).toFixed(2)} km` : `${value.toFixed(1)} m`;
  const add = (parent, tag, value, cls) => { const node = document.createElement(tag); if (cls) node.className = cls; if (value !== undefined) node.textContent = value; parent.appendChild(node); return node; };
  const privacyOn = () => $("privacy-mask").checked;
  const masked = (value, name) => privacyOn() && ["coordinates", "author", "createTime", "updateTime"].includes(name) ? "已遮罩" : text(value);

  function row(parent, label, value) { const dt = add(parent, "dt", label); const dd = add(parent, "dd", value); return [dt, dd]; }
  function pointLatLng(point) { return [point.latitude, point.longitude]; }
  function makePopup(point) { const box = document.createElement("div"); add(box, "strong", `航点 ${text(point.index)}`); row(box, "经度", number(point.longitude, 6)); row(box, "纬度", number(point.latitude, 6)); row(box, "高度", `${text(point.height)} ${text(point.height_mode, "")}`); return box; }

  function drawWaypoint(point, color, group, labels) {
    const marker = L.circleMarker(pointLatLng(point), { radius: 6, color, weight: 2, fillColor: "#fff", fillOpacity: 1 });
    marker.bindPopup(makePopup(point)); marker.on("click", () => renderWaypointDetails(point)); marker.addTo(group);
    const labelNode = document.createElement("span"); labelNode.textContent = text(point.index);
    labels.push(L.marker(pointLatLng(point), { interactive: false, opacity: 1, icon: L.divIcon({ className: "waypoint-label", html: labelNode.outerHTML, iconSize: [24, 20], iconAnchor: [-4, 10] }) }));
  }

  function renderWaypointDetails(point) { const target = $("waypoint-details"); target.replaceChildren(); add(target, "h2", "航点详情"); const dl = add(target, "dl"); row(dl, "编号", text(point.index)); row(dl, "来源", text(point.source)); row(dl, "经度", privacyOn() ? "已遮罩" : number(point.longitude, 6)); row(dl, "纬度", privacyOn() ? "已遮罩" : number(point.latitude, 6)); row(dl, "高度", `${text(point.height)} ${text(point.height_mode, "")}`); row(dl, "速度", point.speed == null ? "—" : `${point.speed} m/s`); row(dl, "航向", text(point.heading)); row(dl, "转弯模式", text(point.turn_mode)); row(dl, "动作", point.actions && point.actions.length ? point.actions.join("、") : "—"); }

  function clearLayers() { [state.routeLayer, state.templateLayer].forEach((layer) => layer && layer.clearLayers()); state.labels.forEach((label) => state.map.removeLayer(label)); state.routeLabels = []; state.templateLabels = []; state.labels = []; state.bounds = []; }
  function renderMap(route) {
    if (!state.map) { state.map = L.map("map", { zoomControl: true, preferCanvas: true }); state.basemap = L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", { maxZoom: 19, attribution: "© OpenStreetMap contributors" }); state.basemap.on("tileerror", () => { $("map-status").textContent = "在线底图不可用，已回退到本地航线"; $("toggle-basemap").checked = false; $("online-map").checked = false; if (state.map.hasLayer(state.basemap)) state.map.removeLayer(state.basemap); }); if ($("online-map").checked) state.basemap.addTo(state.map); state.routeLayer = L.layerGroup().addTo(state.map); state.templateLayer = L.layerGroup().addTo(state.map); wireMapControls(); }
    clearLayers();
    const execution = route.waypoints || [], template = route.template_waypoints || [];
    if (execution.length) { L.polyline(execution.map(pointLatLng), { color: "#2563eb", weight: 4 }).addTo(state.routeLayer); execution.forEach((point, index) => drawWaypoint({ ...point, index: point.index ?? index }, index === 0 ? "#16a34a" : index === execution.length - 1 ? "#dc2626" : "#2563eb", state.routeLayer, state.routeLabels)); }
    if (template.length) { L.polyline(template.map(pointLatLng), { color: "#7c3aed", weight: 3, dashArray: "8 6" }).addTo(state.templateLayer); template.forEach((point, index) => drawWaypoint({ ...point, index: point.index ?? index }, "#7c3aed", state.templateLayer, state.templateLabels)); }
    (route.lines || []).forEach((line) => L.polyline(line.map(pointLatLng), { color: "#7c3aed", weight: 3, dashArray: "8 6" }).addTo(state.templateLayer));
    (route.polygons || []).forEach((polygon) => L.polygon(polygon.map(pointLatLng), { color: "#9333ea", weight: 2, fillColor: "#c084fc", fillOpacity: .18 }).addTo(state.templateLayer));
    state.labels = state.routeLabels.concat(state.templateLabels); const routeBounds = execution.concat(template).map(pointLatLng); const shapeBounds = (route.lines || []).concat(route.polygons || []).flat().map(pointLatLng); state.bounds = routeBounds.concat(shapeBounds);
    state.labels.forEach((label) => label.addTo(state.map)); fitRoute(); $("map-status").textContent = $("online-map").checked ? "本地航线已加载；在线底图已启用" : "本地航线已加载；在线底图已关闭";
  }
  function fitRoute() { if (state.bounds.length) state.map.fitBounds(L.latLngBounds(state.bounds), { padding: [36, 36], maxZoom: 17 }); else state.map.setView([0, 0], 2); }
  function globeHeight(point) { const value = point && point.ellipsoid_height != null ? point.ellipsoid_height : point && point.height != null ? point.height : 0; const numeric = Number(value); return Number.isFinite(numeric) ? numeric : 0; }
  function globePosition(point) { return Cesium.Cartesian3.fromDegrees(Number(point.longitude), Number(point.latitude), globeHeight(point)); }
  function fitGlobe() { if (!state.globe || !state.globeEntities.length) return; const positions = state.globeEntities.map((entity) => entity.position && entity.position.getValue(Cesium.JulianDate.now())).filter(Boolean); if (positions.length) state.globe.camera.flyToBoundingSphere(Cesium.BoundingSphere.fromPoints(positions), { duration: 0.6 }); }
  function ensureGlobe() {
    if (state.globe) return;
    if (!window.Cesium) { $("globe-status").textContent = "3D 引擎加载失败"; return; }
    state.globe = new Cesium.Viewer("globe", { baseLayer: false, terrainProvider: new Cesium.EllipsoidTerrainProvider(), animation: false, timeline: false, baseLayerPicker: false, geocoder: false, homeButton: false, navigationHelpButton: false, sceneModePicker: false, infoBox: false, selectionIndicator: false, fullscreenButton: false });
    Cesium.TileMapServiceImageryProvider.fromUrl("/vendor/cesium/Assets/Textures/NaturalEarthII/")
      .then((provider) => state.globe.imageryLayers.addImageryProvider(provider))
      .catch(() => { $("globe-status").textContent = "本地地球底图加载失败；航线仍可查看"; });
    $("fit-globe").addEventListener("click", fitGlobe);
  }
  function renderGlobe(route) { ensureGlobe(); if (!state.globe) return; state.globe.entities.removeAll(); state.globeEntities = []; const execution = route.waypoints || [], template = route.template_waypoints || []; const addRoute = (points, color, labelPrefix) => { if (!points.length) return; const positions = points.map(globePosition); const line = state.globe.entities.add({ polyline: { positions, width: 4, material: Cesium.Color.fromCssColorString(color), clampToGround: false } }); state.globeEntities.push(line); points.forEach((point, index) => { const position = positions[index]; const entity = state.globe.entities.add({ position, point: { pixelSize: 8, color: Cesium.Color.fromCssColorString(color), outlineColor: Cesium.Color.WHITE, outlineWidth: 2 }, label: { text: `${labelPrefix}${text(point.index ?? index)}`, font: "12px sans-serif", fillColor: Cesium.Color.WHITE, outlineColor: Cesium.Color.BLACK, outlineWidth: 3, style: Cesium.LabelStyle.FILL_AND_OUTLINE, verticalOrigin: Cesium.VerticalOrigin.BOTTOM, pixelOffset: new Cesium.Cartesian2(0, -8), disableDepthTestDistance: Number.POSITIVE_INFINITY } }); state.globeEntities.push(entity); }); }; addRoute(execution, "#2563eb", ""); addRoute(template, "#a855f7", "规-"); (route.lines || []).forEach((line) => { const positions = line.map((point) => Cesium.Cartesian3.fromDegrees(Number(point.longitude), Number(point.latitude), 0)); if (positions.length > 1) state.globeEntities.push(state.globe.entities.add({ polyline: { positions, width: 3, material: Cesium.Color.fromCssColorString("#a855f7"), clampToGround: false } })); }); (route.polygons || []).forEach((polygon) => { const positions = polygon.map((point) => Cesium.Cartesian3.fromDegrees(Number(point.longitude), Number(point.latitude), 0)); if (positions.length > 2) state.globeEntities.push(state.globe.entities.add({ polygon: { hierarchy: positions, material: Cesium.Color.fromCssColorString("#c084fc").withAlpha(0.25), outline: true, outlineColor: Cesium.Color.fromCssColorString("#9333ea") } })); }); fitGlobe(); const hasEllipsoid = execution.concat(template).some((point) => point.ellipsoid_height != null); $("globe-status").textContent = hasEllipsoid ? "本地 3D 航线已加载；使用文件椭球高度，未启用在线地形" : "本地 3D 航线已加载；使用文件高度，未启用在线地形"; }
  function renderDetails(route) { const s = route.statistics || {}; const templateOnly = (route.source_files || []).length === 1 && route.source_files[0] === "template.kml"; $("title").textContent = route.source_file || "KMZ 航线预览"; $("source").textContent = `数据文件：${(route.source_files || []).join("、") || "KMZ 整体"}`; const summary = $("summary"); summary.replaceChildren(); [[text(templateOnly ? s.templateWaypointCount : s.waypointCount, 0), templateOnly ? "规划航点" : "执行航点"], [distance(s.distanceMeters), "航线距离"], [text(s.polygonCount, 0), "区域"]].forEach(([value, label]) => { const span = add(summary, "span"); add(span, "strong", value); add(span, "small", label); }); const dl = $("route-details"); dl.replaceChildren(); row(dl, "模板类型", text(route.template_type)); row(dl, "templateId", text(route.template_id)); row(dl, "waylineId", text(route.wayline_id)); row(dl, "规划高度模式", text(route.height_mode)); row(dl, "执行高度模式", text(route.execute_height_mode)); row(dl, "全局速度", route.global_speed == null ? "—" : `${route.global_speed} m/s`); row(dl, "高度范围", s.minHeight == null ? "—" : `${s.minHeight} ～ ${s.maxHeight}`); row(dl, "速度范围", s.minSpeed == null ? "—" : `${s.minSpeed} ～ ${s.maxSpeed} m/s`); const warning = $("warnings"); warning.replaceChildren(); if ((route.warnings || []).length) { warning.classList.remove("hidden"); add(warning, "strong", "解析提示"); const ul = add(warning, "ul"); route.warnings.forEach((item) => add(ul, "li", item)); } else warning.classList.add("hidden"); }

  function overallFile() { return { name: "KMZ 整体", rawText: "KMZ 是 ZIP 压缩包，包含以下可查看文件：\n\n- template.kml\n- waylines.wpml\n\n请选择具体文件查看 XML 原文。", fields: Object.values(state.document.files).flatMap((file) => file.fields), route: state.document.route }; }
  function renderFileTabs() { const tabs = $("file-tabs"); tabs.replaceChildren(); [[OVERALL_FILE, "KMZ 整体"], ["template.kml", "template.kml"], ["waylines.wpml", "waylines.wpml"]].forEach(([name, label]) => { const button = add(tabs, "button", label); button.disabled = name !== OVERALL_FILE && !state.document.files[name]; button.className = name === state.currentFile ? "active" : ""; button.addEventListener("click", () => selectFile(name)); }); }
  function renderFields(file) { const target = $("field-table"), query = $("field-search").value.trim().toLowerCase(); target.replaceChildren(); file.fields.filter((field) => !query || `${field.name} ${field.label} ${field.path} ${field.file || ""}`.toLowerCase().includes(query)).forEach((field) => { const article = add(target, "article", undefined, "field-row"); const head = add(article, "div", undefined, "field-head"); add(head, "strong", field.label); add(head, "span", field.sourceStatus, field.sourceStatus === "官方文档" ? "known" : "unknown"); add(article, "code", field.name); add(article, "p", `${masked(field.value, field.name)} ${field.unit || ""}`); if (field.valueMeaning) add(article, "p", field.valueMeaning, "value-meaning"); add(article, "p", field.description, "field-description"); add(article, "small", `${field.file ? `${field.file} · ` : ""}${field.path}${field.sourceReference ? ` · 来源 ${field.sourceReference}` : ""}`, "muted"); }); $("catalog-note").textContent = "已按 2026-03-19 DJI WPML 文档收录字段；文档之外的扩展字段仍显示未收录。"; }
  function renderXml(file) { let value = file.rawText; if (privacyOn()) value = value.replace(/(<(?:[\w.-]+:)?(?:author|coordinates|createTime|updateTime)>)[\s\S]*?(<\/[^>]+>)/gi, "$1已遮罩$2"); $("xml-source").textContent = value; }
  function selectFile(name) { state.currentFile = name; renderFileTabs(); const file = name === OVERALL_FILE ? overallFile() : state.document.files[name]; const route = file.route || state.document.route; state.currentRoute = route; renderDetails(route); renderMap(route); if (state.globe) renderGlobe(route); renderFields(file); renderXml(file); }
  function switchView(view) { state.view = view; document.querySelectorAll(".view-tabs button").forEach((button) => button.classList.toggle("active", button.dataset.view === view)); ["map", "globe", "fields", "xml"].forEach((name) => $(`${name}-view`).classList.toggle("hidden", name !== view)); if (view === "map" && state.map) setTimeout(() => state.map.invalidateSize(), 0); if (view === "globe") { ensureGlobe(); setTimeout(() => { if (state.globe) { state.globe.resize(); if (state.currentRoute) renderGlobe(state.currentRoute); } }, 0); } }
  function wireMapControls() { $("toggle-basemap").addEventListener("change", (event) => { if (event.target.checked && $("online-map").checked) state.basemap.addTo(state.map); else state.map.removeLayer(state.basemap); }); $("toggle-route").addEventListener("change", (event) => { event.target.checked ? state.routeLayer.addTo(state.map) : state.map.removeLayer(state.routeLayer); state.routeLabels.forEach((label) => event.target.checked ? label.addTo(state.map) : state.map.removeLayer(label)); }); $("toggle-template").addEventListener("change", (event) => { event.target.checked ? state.templateLayer.addTo(state.map) : state.map.removeLayer(state.templateLayer); state.templateLabels.forEach((label) => event.target.checked ? label.addTo(state.map) : state.map.removeLayer(label)); }); $("toggle-labels").addEventListener("change", (event) => state.labels.forEach((label) => event.target.checked ? label.addTo(state.map) : state.map.removeLayer(label))); $("fit-route").addEventListener("click", fitRoute); }
  $("online-map").addEventListener("change", (event) => { $("toggle-basemap").checked = event.target.checked; if (event.target.checked && state.map && state.basemap) { state.basemap.addTo(state.map); $("map-status").textContent = "本地航线已加载；正在请求在线底图"; } else if (state.map && state.basemap) { state.map.removeLayer(state.basemap); $("map-status").textContent = "本地航线已加载；在线底图已关闭"; } }); $("field-search").addEventListener("input", () => state.currentFile && renderFields(state.currentFile === OVERALL_FILE ? overallFile() : state.document.files[state.currentFile])); $("copy-xml").addEventListener("click", () => navigator.clipboard.writeText($("xml-source").textContent)); document.querySelectorAll(".view-tabs button").forEach((button) => button.addEventListener("click", () => switchView(button.dataset.view)));
  $("privacy-mask").addEventListener("change", () => { if (state.currentFile) { const file = state.currentFile === OVERALL_FILE ? overallFile() : state.document.files[state.currentFile]; renderFields(file); renderXml(file); } });
  api("/api/document").then((documentData) => { state.document = documentData; state.currentFile = OVERALL_FILE; renderFileTabs(); selectFile(state.currentFile); }).catch((error) => { $("map-status").textContent = error.message; $("source").textContent = "无法加载 KMZ 文档"; });
}());
